In [1]:
from Utils import *
from classifier.CNNClassifier import CNNClassifier
from classifier.Classifier import Classifier
from classifier.ConstantClassifier import ConstantClassifier
from classifier.LinearClassifier import LinearClassifier
from classifier.RFClassifier import RFClassifier
from classifier.SNNClassifier import SNNClassifier
from Settings import *
from sklearn.model_selection import train_test_split
from main import run_for_classifier

SAVE=True
LOAD=False

Using TensorFlow backend.


In [2]:
features_with_label = files_to_features_with_labels(list_files(AUDIO_FILES_DIR))
train_set, test_set = train_test_split(features_with_label, random_state=SEED, train_size=TRAIN_PERCENT, test_size=1-TRAIN_PERCENT)

In [3]:
features_train = extract_features(train_set)
labels_train = extract_labels(train_set)

In [39]:
features_train.shape[0]

2675

In [22]:
import pandas as pd

In [43]:
df = pd.DataFrame(features_train[0])

In [52]:
labels = pd.DataFrame(np.zeros(127))

In [53]:
labels1 = pd.DataFrame(np.zeros(50)+1)

In [59]:
labels_train[0]

1

In [62]:
if labels_train[1] == 0:
    print(0)
else:
    print(1)

1


In [69]:
train_df = pd.DataFrame(features_train[0])
train_label = pd.DataFrame(np.zeros(train_df.shape[0]))
if labels_train[0] == 1:
    train_label = train_label+1

In [70]:
#train_label

In [71]:
for i in range(1, features_train.shape[0]):
    dfTemp = pd.DataFrame(features_train[i])
    train_df = train_df.append(dfTemp, ignore_index=True)
    labelTemp = pd.DataFrame(np.zeros(dfTemp.shape[0]))
    if labels_train[i] == 1:
        labelTemp = labelTemp+1
    train_label = train_label.append(labelTemp)

In [72]:
train_df.shape

(178956, 20)

In [73]:
train_label.shape

(178956, 1)

In [46]:
df.shape

(178956, 20)

In [26]:
df = pd.DataFrame(features_train[0])

In [31]:
df1 = pd.DataFrame(features_train[1])

In [34]:
df2 = df.append(df1)

In [35]:
df2.shape

(179, 20)

In [37]:
train_data = np.array(df2)

In [38]:
train_data.shape

(179, 20)

In [24]:
trainData = pd.DataFrame(features_train)

In [25]:
trainData.shape

(2675, 1)

In [19]:
features_train[0].shape

(127, 20)

In [20]:
features_train[1].shape

(52, 20)

In [21]:
features_train[0], features_train[1]

ValueError: operands could not be broadcast together with shapes (127,20) (52,20) 

In [4]:
import plda
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
from numpy import random,mat

In [74]:
classifier = plda.Classifier()

In [ ]:
train_df = pd.DataFrame(features_train[0])
train_label = pd.DataFrame(np.zeros(train_df.shape[0]))

In [75]:
print(train_df.shape, train_label.shape)


(178956, 20) (178956, 1)


In [77]:
np.array(train_df)

array([[0.68070254, 0.47540527, 0.61192208, ..., 0.40995414, 0.39588086,
        0.41895868],
       [0.77501817, 0.47743728, 0.62427862, ..., 0.41562028, 0.40069454,
        0.41986239],
       [0.75638254, 0.48190874, 0.63091752, ..., 0.41835072, 0.40872033,
        0.42232574],
       ...,
       [0.31728625, 0.51517216, 0.48357028, ..., 0.44187902, 0.43103272,
        0.39526543],
       [0.32280107, 0.51535633, 0.50492888, ..., 0.40199477, 0.36728799,
        0.39610247],
       [0.31626533, 0.50685449, 0.53579937, ..., 0.39866276, 0.3447906 ,
        0.37878463]])

In [76]:
print(np.array(train_df).shape, np.array(train_label).shape)

(178956, 20) (178956, 1)


In [84]:
train_df.values

array([[0.68070254, 0.47540527, 0.61192208, ..., 0.40995414, 0.39588086,
        0.41895868],
       [0.77501817, 0.47743728, 0.62427862, ..., 0.41562028, 0.40069454,
        0.41986239],
       [0.75638254, 0.48190874, 0.63091752, ..., 0.41835072, 0.40872033,
        0.42232574],
       ...,
       [0.31728625, 0.51517216, 0.48357028, ..., 0.44187902, 0.43103272,
        0.39526543],
       [0.32280107, 0.51535633, 0.50492888, ..., 0.40199477, 0.36728799,
        0.39610247],
       [0.31626533, 0.50685449, 0.53579937, ..., 0.39866276, 0.3447906 ,
        0.37878463]])

In [86]:
train_label.values

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [85]:
np.array(train_df)

array([[0.68070254, 0.47540527, 0.61192208, ..., 0.40995414, 0.39588086,
        0.41895868],
       [0.77501817, 0.47743728, 0.62427862, ..., 0.41562028, 0.40069454,
        0.41986239],
       [0.75638254, 0.48190874, 0.63091752, ..., 0.41835072, 0.40872033,
        0.42232574],
       ...,
       [0.31728625, 0.51517216, 0.48357028, ..., 0.44187902, 0.43103272,
        0.39526543],
       [0.32280107, 0.51535633, 0.50492888, ..., 0.40199477, 0.36728799,
        0.39610247],
       [0.31626533, 0.50685449, 0.53579937, ..., 0.39866276, 0.3447906 ,
        0.37878463]])

In [83]:
train_df.shape

(178956, 20)

In [88]:
classifier.fit_model(train_df.values, train_label.values, n_principal_components=1)

(178956, 20)
[[0.68070254 0.47540527 0.61192208 ... 0.40995414 0.39588086 0.41895868]
 [0.77501817 0.47743728 0.62427862 ... 0.41562028 0.40069454 0.41986239]
 [0.75638254 0.48190874 0.63091752 ... 0.41835072 0.40872033 0.42232574]
 ...
 [0.31728625 0.51517216 0.48357028 ... 0.44187902 0.43103272 0.39526543]
 [0.32280107 0.51535633 0.50492888 ... 0.40199477 0.36728799 0.39610247]
 [0.31626533 0.50685449 0.53579937 ... 0.39866276 0.3447906  0.37878463]]


ValueError: expected square matrix

In [16]:
labels_train

array([1, 1, 1, ..., 0, 0, 0])

In [14]:
features_train[0].shape

(127, 20)

In [15]:
features_train[1].shape

(52, 20)

In [13]:
features_train

array([array([[0.68070254, 0.47540527, 0.61192208, ..., 0.40995414, 0.39588086,
        0.41895868],
       [0.77501817, 0.47743728, 0.62427862, ..., 0.41562028, 0.40069454,
        0.41986239],
       [0.75638254, 0.48190874, 0.63091752, ..., 0.41835072, 0.40872033,
        0.42232574],
       ...,
       [0.30291971, 0.58938896, 0.54612862, ..., 0.36057181, 0.46820339,
        0.41672315],
       [0.29783974, 0.56977407, 0.54070181, ..., 0.42241812, 0.49122132,
        0.39464192],
       [0.28331963, 0.55951368, 0.57182201, ..., 0.3925112 , 0.4594885 ,
        0.39984143]]),
       array([[0.79154606, 0.47070665, 0.62033734, ..., 0.40973844, 0.38939352,
        0.41045938],
       [0.78647905, 0.47926179, 0.63623767, ..., 0.43855846, 0.38625923,
        0.39764628],
       [0.72634122, 0.47382993, 0.60589375, ..., 0.30442197, 0.44752815,
        0.4392363 ],
       ...,
       [0.2360081 , 0.5217082 , 0.59980882, ..., 0.46095102, 0.47208483,
        0.36998096],
       [0.24837287, 

In [9]:
features_train

array([array([[0.68070254, 0.47540527, 0.61192208, ..., 0.40995414, 0.39588086,
        0.41895868],
       [0.77501817, 0.47743728, 0.62427862, ..., 0.41562028, 0.40069454,
        0.41986239],
       [0.75638254, 0.48190874, 0.63091752, ..., 0.41835072, 0.40872033,
        0.42232574],
       ...,
       [0.30291971, 0.58938896, 0.54612862, ..., 0.36057181, 0.46820339,
        0.41672315],
       [0.29783974, 0.56977407, 0.54070181, ..., 0.42241812, 0.49122132,
        0.39464192],
       [0.28331963, 0.55951368, 0.57182201, ..., 0.3925112 , 0.4594885 ,
        0.39984143]]),
       array([[0.79154606, 0.47070665, 0.62033734, ..., 0.40973844, 0.38939352,
        0.41045938],
       [0.78647905, 0.47926179, 0.63623767, ..., 0.43855846, 0.38625923,
        0.39764628],
       [0.72634122, 0.47382993, 0.60589375, ..., 0.30442197, 0.44752815,
        0.4392363 ],
       ...,
       [0.2360081 , 0.5217082 , 0.59980882, ..., 0.46095102, 0.47208483,
        0.36998096],
       [0.24837287, 

In [8]:
labels_train

array([1, 1, 1, ..., 0, 0, 0])

In [7]:
classifier.fit_model(features_train, labels_train, n_principal_components=5)

(2675,)
[array([[0.68070254, 0.47540527, 0.61192208, ..., 0.40995414, 0.39588086,
        0.41895868],
       [0.77501817, 0.47743728, 0.62427862, ..., 0.41562028, 0.40069454,
        0.41986239],
       [0.75638254, 0.48190874, 0.63091752, ..., 0.41835072, 0.40872033,
        0.42232574],
       ...,
       [0.30291971, 0.58938896, 0.54612862, ..., 0.36057181, 0.46820339,
        0.41672315],
       [0.29783974, 0.56977407, 0.54070181, ..., 0.42241812, 0.49122132,
        0.39464192],
       [0.28331963, 0.55951368, 0.57182201, ..., 0.3925112 , 0.4594885 ,
        0.39984143]])
 array([[0.79154606, 0.47070665, 0.62033734, ..., 0.40973844, 0.38939352,
        0.41045938],
       [0.78647905, 0.47926179, 0.63623767, ..., 0.43855846, 0.38625923,
        0.39764628],
       [0.72634122, 0.47382993, 0.60589375, ..., 0.30442197, 0.44752815,
        0.4392363 ],
       ...,
       [0.2360081 , 0.5217082 , 0.59980882, ..., 0.46095102, 0.47208483,
        0.36998096],
       [0.24837287, 0.532

AssertionError: 

In [8]:
len(features_train.shape)

1

In [ ]:
classifier.fit_model(features_train, labels_train, n_principal_components=5)

predictions, log_p_predictions = classifier.predict(testing_data)

In [ ]:
print(testing_data.shape, testing_labels.shape)

In [2]:


def test_classifier(classifier : Classifier) -> None:
    """
    Wrapper for method run_for_classifier.
    :param classifier: The classifier to test
    """
    one_d = not isinstance(classifier, CNNClassifier)
    run_for_classifier(classifier, test_set=test_set, train_set=train_set, save=SAVE, load=LOAD, one_d=one_d)

In [3]:
test_classifier(RFClassifier(n_estimators=10))

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9805680119581465
Test accuracy - samples : 0.8075283937263386


run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9805680119581465
Test accuracy - samples : 0.8075283937263386

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9819078947368421
Test accuracy - samples : 0.8106407598476447

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9748427672955975
Test accuracy - samples : 0.7540060177734238

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.948220064724919
Test accuracy - samples : 0.7349437337341006

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9722222222222222
Test accuracy - samples : 0.7556776128705543

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9754385964912281
Test accuracy - samples : 0.7609640299348194

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9820143884892086
Test accuracy - samples : 0.7675503799141064

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9560439560439561
Test accuracy - samples : 0.767567787639443

In [4]:
test_classifier(RFClassifier(n_estimators=100))

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9745889387144993
Test accuracy - samples : 0.8410383991346674


run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9802631578947368
Test accuracy - samples : 0.8487054626102888

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9779874213836478
Test accuracy - samples : 0.7998390595479673

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9546925566343042
Test accuracy - samples : 0.7787471133756094

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9756944444444444
Test accuracy - samples : 0.7995013828834093

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9719298245614035
Test accuracy - samples : 0.8007564174780719

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9646643109540636
Test accuracy - samples : 0.7948184038761863

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9820143884892086
Test accuracy - samples : 0.8051288404360754

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.978021978021978
Test accuracy - samples : 0.8037619086393616

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.984313725490196
Test accuracy - samples : 0.8058165548098434

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9740740740740741
Test accuracy - samples : 0.7995526496902959

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9839357429718876
Test accuracy - samples : 0.8234393987128134

In [4]:
test_classifier(RFClassifier(n_estimators=10))

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9717741935483871
Test accuracy - samples : 0.7775365268919346


run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9873417721518988
Test accuracy - samples : 0.8189973852673339

In [7]:
def test_classifier(classifier : Classifier) -> None:
    """
    Wrapper for method run_for_classifier.
    :param classifier: The classifier to test
    """
    one_d = not isinstance(classifier, CNNClassifier)
    run_for_classifier(classifier)

In [8]:
def run_for_classifier(classifier: Classifier, one_d: bool = False, cv: int = None,
                       train_set: np.ndarray = None,
                       test_set: np.ndarray = None,
                       save: bool = True,
                       load: bool = True) -> None:
    """
    Test a given classifier and print the results.
    :param classifier: The classifier to test
    :param one_d: If the features are to be flattened or not
    :param cv: If >1, will run cross validation(on samples) with the given number of splits on the classifier
    :param train_set: Optionally given to save time if run_for_classifier is called multiple times
    :param test_set: Optionally given to save time if run_for_classifier is called multiple times
    :param save: If the classifier is to be saved to a file
    :param load: If the classifier is to be loaded from a file
    """
    print("run_for_classifier..")
    #folder = "data/TIMIT"
    #folder = "predict_dir/DR5"
    folder = "predict_dir/Test"
    #folder = "data/TIMIT/TEST/DR5"
    if train_set is None or test_set is None:
        features_with_label = files_to_features_with_labels(list_files(folder))
        test_set = features_with_label
    print("Finished loading/creating features")
    print("Using classifier " + classifier.get_classifier_name())
    classifier.load(MODELS_DIR + classifier.get_classifier_name() + DUMP_EXT)
    print("ModePath:"+MODELS_DIR + classifier.get_classifier_name() + DUMP_EXT)
    print("Predicting on files...")
    predictions = []
    test_labels = extract_labels(test_set)
    for feat_label_tuple in test_set:
        features = feat_label_tuple[0]        
        results = classifier.predict(features)
        predictions.append(return_majority(results))
    predictions = np.asarray(predictions)
    print(predictions)
    print(test_labels)
    if not os.path.isdir(OUTPUT_DIR):
        os.mkdir(OUTPUT_DIR)
    with open(OUTPUT_DIR + classifier.get_classifier_name() + "_output.txt", "w") as output_file:
        output_file.writelines([str(pred) + "\n" for pred in predictions])

    # Per sample predictions
    print("Predicting on samples...")
    if one_d:
        transformed_test_set = to_1d(test_set)
    else:
        transformed_test_set = to_2d(test_set)

    samples_features = extract_features(transformed_test_set)
    samples_predictions = classifier.predict(samples_features)
    samples_test_labels = extract_labels(transformed_test_set)
    print(samples_predictions)
    print(samples_test_labels)
    #prediction = classMode.predict(samples_features)
    #print("New Test accuracy - files : " + str(get_accuracy(predictions, test_labels)))
    print("Test accuracy - files : " + str(get_accuracy(predictions, test_labels)))
    print("Test accuracy - samples : " + str(get_accuracy(samples_predictions, samples_test_labels)))

In [5]:
test_classifier(RFClassifier(n_estimators=100))

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9751243781094527
Test accuracy - samples : 0.8437397305290831


In [5]:
test_classifier(RFClassifier(n_estimators=100))

run_for_classifier..
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
[1 1]
[0 0]
Predicting on samples...
[1 1 1 ... 1 1 1]
[0 0 0 ... 0 0 0]
Test accuracy - files : 0.0
Test accuracy - samples : 0.12033067973055726


### Preliminary informations
##### Disclaimer : The neural networks results may vary a bit when re-training them due to some randomness in tensorflow-gpu / cuDNN.

The models were trained on a computer with an i7-6700K, 16GB RAM and a GTX 1070.    
The main libraries used are Keras with tensorflow backend, librosa, scikit-learn.    
###### If you want to avoid retraining every classifier, set LOAD=True above. The RF with 100 estimators couldn't be pushed to the repository due to its file size though.

Let's begin by explaining how to measure the performance of the classifiers. There are two main metrics :    
- The sample accuracy : It's the accuracy for predicting the label of a sample of a file. For the CNN, it's a window of 10 samples.
- The file accuracy : It's the accuracy for predicting the label of a file. The label is simply calculated by taking the most predicted label on all the samples of the file.

The files were cut in samples of 20 MFCC features using the librosa library. This was mostly sufficient to allow the training on most of the classifiers. No preprocessing was done on the audio files or the MFCC features except normalizing them.    
Some more preprocessing was done to allow the files to be fed to a CNN (cutting the files in windows).

The files were separated in train set and test set using 80/20 proportions. There are 2703 files in total.

### Constant Classifier
This classifier always predicts male.

In [3]:
test_classifier(ConstantClassifier())

run_for_classifier
Finished loading/creating features
Using classifier ConstantClassifierTimit
Training ConstantClassifierTimit
Saved ConstantClassifierTimit
ModePath:models/ConstantClassifierTimit.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.5021645021645021
Test accuracy - samples : 0.45987015430937145


This gives us some information on the files as well as a baseline :     
- The files are distributed nearly uniformly between male and female
- When taking duration into account, the files are distributed even more closely half male / half female

This means that it is not really needed to perform balancing between the train and test set, assuming we distribute the files randomly between them.

### Linear SVC
This classifier is created using SVM with a linear kernel. It could serve as another simple baseline.

In [5]:
test_classifier(LinearClassifier(c=1))

run_for_classifier
Finished loading/creating features
Using classifier LinearClassifier - C1
Training LinearClassifier - C1
Saved LinearClassifier - C1
ModePath:models/LinearClassifier - C1.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9233870967741935
Test accuracy - samples : 0.7227574976251866


In [ ]:
run_for_classifier
Finished loading/creating features
Using classifier LinearClassifier - C1
Training LinearClassifier - C1
Saved LinearClassifier - C1
ModePath:models/LinearClassifier - C1.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9307359307359307
Test accuracy - samples : 0.7412965750846819

 Here, the linear SVC returns quite mediocre results, having a file-accuracy of only 82%, and a worse sample accuracy of 70%.    
Trying to increase the C parameter to 1000 makes the classifier not converge (or very slowly. When tested earlier, it hadn't converged in 10000 iterations).    
It isn't surprising that a linear classifier would fail on this problem, as it is probably non-linear. Improving the preprocessing as well as doing features selection could improve the result.

In [6]:
test_classifier(LinearClassifier(c=1000))

run_for_classifier
Finished loading/creating features
Using classifier LinearClassifier - C1000
Training LinearClassifier - C1000
Saved LinearClassifier - C1000
ModePath:models/LinearClassifier - C1000.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.5604838709677419
Test accuracy - samples : 0.6452254941873614


In [ ]:
run_for_classifier
Finished loading/creating features
Using classifier LinearClassifier - C1000
Training LinearClassifier - C1000
Saved LinearClassifier - C1000
ModePath:models/LinearClassifier - C1000.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.5021645021645021
Test accuracy - samples : 0.48367519759126837

### RandomForestClassifier
Let's test RandomForestClassifiers, which are known to be quite accurate when features are well-defined and results are dependent on these features, which should be the case with the MFCC features and the speaker's gender.

In [5]:
test_classifier(RFClassifier(n_estimators=10))

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 10 - max_depth None
Training RFClassifier - n_est 10 - max_depth None
Saved RFClassifier - n_est 10 - max_depth None
ModePath:models/RFClassifier - n_est 10 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9800995024875622
Test accuracy - samples : 0.8138898017307482


Here, we can already see that the files accuracy is nearly perfect (in fact, only 1 file is mispredicted). The sample accuracy could be better though.    
Let's try to improve it by increasing the number of trees. We may also get a 100% file accuracy by doing this.

In [3]:
test_classifier(RFClassifier(n_estimators=100))

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Training RFClassifier - n_est 100 - max_depth None
Saved RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9914529914529915
Test accuracy - samples : 0.836785648233771


It doesn't seem to improve much and isn't really worth it given the increase in memory and time consumption. It is better, as expected (averaging over more votes should lead to a better result), but not needed for the files accuracy.    
Let's try with 1 and 5 trees to see if we can go lower than 10 while preserving the accuracy :

In [5]:
test_classifier(RFClassifier(n_estimators=5))
print("\n")
test_classifier(RFClassifier(n_estimators=1))

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 5 - max_depth None
Training RFClassifier - n_est 5 - max_depth None
Saved RFClassifier - n_est 5 - max_depth None
ModePath:models/RFClassifier - n_est 5 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9786184210526315
Test accuracy - samples : 0.7906561882262186


run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 1 - max_depth None
Training RFClassifier - n_est 1 - max_depth None
Saved RFClassifier - n_est 1 - max_depth None
ModePath:models/RFClassifier - n_est 1 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9671052631578947
Test accuracy - samples : 0.7200231425678607


run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 5 - max_depth None
Training RFClassifier - n_est 5 - max_depth None
Saved RFClassifier - n_est 5 - max_depth None
ModePath:models/RFClassifier - n_est 5 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9434628975265018
Test accuracy - samples : 0.7369559123853762


run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 1 - max_depth None
Training RFClassifier - n_est 1 - max_depth None
Saved RFClassifier - n_est 1 - max_depth None
ModePath:models/RFClassifier - n_est 1 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.950530035335689
Test accuracy - samples : 0.6760501341448765

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 5 - max_depth None
Training RFClassifier - n_est 5 - max_depth None
Saved RFClassifier - n_est 5 - max_depth None
ModePath:models/RFClassifier - n_est 5 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.974025974025974
Test accuracy - samples : 0.7659013925479865


run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 1 - max_depth None
Training RFClassifier - n_est 1 - max_depth None
Saved RFClassifier - n_est 1 - max_depth None
ModePath:models/RFClassifier - n_est 1 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.987012987012987
Test accuracy - samples : 0.7046010538200979

Strangely enough, we get a really good result with even only one tree. The sample accuracy decreases quite a bit obviously, but the file accuracy is still very good. This means that there are features which are very relevant to finding the speaker's gender.   
With 5 trees, the file accuracy is the same as the one with 10 trees.    
The RandomForest seems to be very well suited for this problem, as expected. What was less expected was that such a performance was obtained using a very small number of estimators.    
RandomForest is therefore a very efficient and easy way to solve this problem.

### Shallow Neural Network
Let's try using a shallow neural network with only a single fully-connected hidden layer.    
In theory, such a simple neural net should be able to approximate every function perfectly, but in practice, a deep neural network usually yields better results than a wide one.

In [6]:
test_classifier(SNNClassifier(num_units=64, verbose=1))

run_for_classifier
Finished loading/creating features
Using classifier SNNClassifier - units 64
Training SNNClassifier - units 64
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                1344      
_________________________________________________________________
p_re_lu_1 (PReLU)            (None, 64)                64        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 1,473
Trainable params: 1,473
Non-trainable params: 0
_________________________________________________________________
None
Train on 81080 samples, validate on 20270 samples
Epoch 1/300
81080/81080 [==============================] - 1s 9us/step - loss: 0.6258 -

Epoch 53/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.4174 - acc: 0.7905 - val_loss: 0.4669 - val_acc: 0.7653
Epoch 54/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.4170 - acc: 0.7915 - val_loss: 0.4671 - val_acc: 0.7626
Epoch 55/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.4158 - acc: 0.7920 - val_loss: 0.4705 - val_acc: 0.7571
Epoch 56/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.4159 - acc: 0.7906 - val_loss: 0.4784 - val_acc: 0.7485
Epoch 57/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.4153 - acc: 0.7925 - val_loss: 0.4749 - val_acc: 0.7564
Epoch 58/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.4148 - acc: 0.7909 - val_loss: 0.4718 - val_acc: 0.7556
Epoch 59/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.4145 - acc: 0.7908 - val_loss: 0.4712 - val_acc: 0.7560
Epoch 60/300
81080/81080 [========

81080/81080 [==============================] - 1s 8us/step - loss: 0.3943 - acc: 0.8058 - val_loss: 0.4560 - val_acc: 0.7700
Epoch 00111: early stopping
Saved SNNClassifier - units 64
ModePath:models/SNNClassifier - units 64.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.9540636042402827
Test accuracy - samples : 0.7851279381732271


In [ ]:
Test accuracy - files : 0.9800995024875622
Test accuracy - samples : 0.8527768649359185

We already get a nearly perfect accuracy for files, which is very impressive with only 64 units. This probably means that the function to approximate / the problem is not really complex, but still non-linear.    
Let's try to improve the accuracy by increasing the number of units in the dense layer.

In [7]:
test_classifier(SNNClassifier(num_units=128, verbose=1))

run_for_classifier
Finished loading/creating features
Using classifier SNNClassifier - units 128
Training SNNClassifier - units 128
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 128)               2688      
_________________________________________________________________
p_re_lu_2 (PReLU)            (None, 128)               128       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 129       
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 2,945
Trainable params: 2,945
Non-trainable params: 0
_________________________________________________________________
None
Train on 81080 samples, validate on 20270 samples
Epoch 1/300
81080/81080 [==============================] - 1s 10us/step - loss: 0.615

Epoch 53/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.4003 - acc: 0.7996 - val_loss: 0.4506 - val_acc: 0.7684
Epoch 54/300
81080/81080 [==============================] - 1s 9us/step - loss: 0.4000 - acc: 0.7994 - val_loss: 0.4606 - val_acc: 0.7624
Epoch 55/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.3995 - acc: 0.8012 - val_loss: 0.4571 - val_acc: 0.7667
Epoch 56/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.3974 - acc: 0.8023 - val_loss: 0.4561 - val_acc: 0.7699
Epoch 57/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.3974 - acc: 0.8027 - val_loss: 0.4624 - val_acc: 0.7614
Epoch 58/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.3965 - acc: 0.8028 - val_loss: 0.4523 - val_acc: 0.7662
Epoch 59/300
81080/81080 [==============================] - 1s 8us/step - loss: 0.3958 - acc: 0.8034 - val_loss: 0.4552 - val_acc: 0.7709
Epoch 60/300
81080/81080 [========

As expected, the sample accuracy is ~1% better, and the file accuracy is now perfect.

In [11]:
test_classifier(SNNClassifier(num_units=256, verbose=1))

Finished loading/creating features
Using classifier SNNClassifier - units 256
Training SNNClassifier - units 256
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 256)               5376      
_________________________________________________________________
p_re_lu_3 (PReLU)            (None, 256)               256       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 257       
_________________________________________________________________
activation_3 (Activation)    (None, 1)                 0         
Total params: 5,889
Trainable params: 5,889
Non-trainable params: 0
_________________________________________________________________
None
Train on 384480 samples, validate on 96121 samples
Epoch 1/300
384480/384480 [==============================] - 4s 9us/step - loss: 0.5089 - acc: 0.7378 -

We gain a very marginal increase in sample accuracy. File accuracy is still perfect. Increasing the model complexity further shouldn't yield any worthy increase in accuracy, as this model (and even the one with 128 units) is complex enough to accurately class the audio files.

I decided to not add any Dropout or regularization to the network because, as we can see in the results, there is little to no overfitting.

### Convolutional Neural Network
The CNN Classifier was more difficult to implement.    
First, the input is different compared to the other classifiers. We need to give identical 2D inputs to the network, but the number of samples per file varies a lot.    
- The first attempt was padding the smaller files to the size of the biggest one by adding 0s features. Due to the difference in size, the network couldn't learn anything, as most of the data was empty (smallest file has 46 samples, biggest has around 1200).   
- The next attempt was cutting the files into smaller windows of 46 samples (and potentially padding the last sample of the file). The next cell is the (reduced) output of a run using this strategy.    
- The current one is to cut the files into windows of 10 samples. We'll see the result later.

As the purpose of this classifier is to be a deep neural network, I decided to put two convolutional layers along with two max pooling, followed by two denses layers and an output layer. The whole network can be seen in the following cell.    
Due to the number of parameters for this network (parameters in each layer, layout of the network, etc), most of these are heuristically chosen from a previous project on road segmentation. 

About design decisions :    
- Batch normalization is used for faster and better training
- Prelu activation is used instead of relu for potential better results
- Glorot Normal initialization is used, but it seems that it is a matter of preference between uniform and normal and has no real impact on performance
- Dropouts are used after max pooling and dense layers to reduce overfitting
- Kernel regularizers are used on the convolution and dense layers to reduce overfitting
- (Both dropouts and regularizers were added after checking that the network could learn perfectly the training set)

As expected, the CNN got a really good score for both file and sample accuracy, but it strangely was not perfect like the SNN and is even a bit worse than the random forest. Moreover, the sample accuracy can not really be compared to the one obtained with the previous classifiers, as the CNN has more context (46 times more information than the other classifiers).  
The next run obtains a perfect file score by reducing the window size.

In [6]:
test_classifier(CNNClassifier(verbose=1))

run_for_classifier
Finished loading/creating features
Using classifier CNNClassifier
Training CNNClassifier
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_1 (Batch (None, 10, 20, 1)         4         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 8, 18, 32)         320       
_________________________________________________________________
p_re_lu_1 (PReLU)            (None, 8, 18, 32)         4608      
_________________________________________________________________
batch_normalization_2 (Batch (None, 8, 18, 32)         128       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 17, 32)         0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 7, 17, 32)         0         
__________________________________

Epoch 37/300
14134/14134 [==============================] - 13s 905us/step - loss: 0.4760 - acc: 0.8313 - val_loss: 0.4772 - val_acc: 0.8356
Epoch 38/300
14134/14134 [==============================] - 13s 894us/step - loss: 0.4846 - acc: 0.8270 - val_loss: 0.4653 - val_acc: 0.8475
Epoch 39/300
14134/14134 [==============================] - 13s 897us/step - loss: 0.4886 - acc: 0.8335 - val_loss: 0.4625 - val_acc: 0.8534
Epoch 40/300
14134/14134 [==============================] - 12s 881us/step - loss: 0.4793 - acc: 0.8318 - val_loss: 0.4802 - val_acc: 0.8220
Epoch 41/300
14134/14134 [==============================] - 12s 879us/step - loss: 0.4752 - acc: 0.8356 - val_loss: 0.4912 - val_acc: 0.8274
Epoch 42/300
14134/14134 [==============================] - 12s 880us/step - loss: 0.4821 - acc: 0.8321 - val_loss: 0.4563 - val_acc: 0.8565
Epoch 43/300
14134/14134 [==============================] - 13s 903us/step - loss: 0.4789 - acc: 0.8337 - val_loss: 0.4507 - val_acc: 0.8531
Epoch 44/300


Epoch 94/300
14134/14134 [==============================] - 13s 898us/step - loss: 0.2750 - acc: 0.8985 - val_loss: 0.3347 - val_acc: 0.8772
Epoch 95/300
14134/14134 [==============================] - 12s 884us/step - loss: 0.2720 - acc: 0.9002 - val_loss: 0.3328 - val_acc: 0.8775
Epoch 96/300
14134/14134 [==============================] - 12s 882us/step - loss: 0.2750 - acc: 0.9014 - val_loss: 0.3368 - val_acc: 0.8769
Epoch 97/300
14134/14134 [==============================] - 12s 884us/step - loss: 0.2739 - acc: 0.9005 - val_loss: 0.3291 - val_acc: 0.8769
Epoch 98/300
14134/14134 [==============================] - 13s 885us/step - loss: 0.2693 - acc: 0.9053 - val_loss: 0.3341 - val_acc: 0.8766
Epoch 99/300
14134/14134 [==============================] - 12s 882us/step - loss: 0.2763 - acc: 0.8995 - val_loss: 0.3326 - val_acc: 0.8775
Epoch 100/300
14134/14134 [==============================] - 13s 888us/step - loss: 0.2729 - acc: 0.9006 - val_loss: 0.3343 - val_acc: 0.8803
Epoch 101/30

In [ ]:
Test accuracy - files : 0.9798387096774194
Test accuracy - samples : 0.8597168597168597

In [ ]:
Test accuracy - files : 0.950530035335689
Test accuracy - samples : 0.8377042949448879

Now, by using windows of size 10, we get a the same result as the RandomForest for file accuracy (1 mispredicted file), which is better than with a window size of 46. It is probably mainly due to averaging over more samples : As the per sample accuracy is still very high, averaging over them allows for a very good score. In theory, as long as we have a per sample accuracy >50% and a very high number of samples per file, the predictions should be perfect. It is not always the case in practice due to the number of samples per file. 


100% files accuracy should be obtainable by tuning the parameters or changing the layout.      

Compared to the other classifiers however, it is slower to train, more memory hungry, and therefore seems a bit overkill for this task, given than a simple neural net with a single hidden layer obtains file predictions results better than this one.    

### Dumps size
If we compare the performance/file size metric of the classifiers, we see that the SNN is easily the best one, the 256 units network weighing only 96Ko, compared to the 12Mo for the 10 estimators RandomForest or the 23Mo CNN. The linear SVC only weighs 1Ko, but gives bad results.

### Other considerations
- I've also added a cross-validation method to test the classifiers on samples, but due to the time it takes to execute it, I decided to leave it out.
- I have considered data augmentation, but given the results we've already obtained, this isn't at all necessary for this problem and would only be wasted time.

### Conclusion

In conclusion, we can rate the classifiers like this : 
- The winner is obviously the SNN. The complexity of designing it is really low, the file size is also very small, and it gets a perfect result.
- The second one would be the RandomForest. The design complexity is non-existant, the file size is moderately high but still very manageable for a low number of trees, and it gets a nearly perfect result.
- The third is the CNN. Although the design complexity is high due to the number of parameters we can change and layouts we can do, and the file size is higher than the others, it gets a nearly score. It is totally unnecessary to implement such a complex network for this problem though.
- The fourth is the linear SVC, because even though the design complexity and file size is null, the results are bad.
- For obvious reasons, the constant classifier is the last one.

In short, a more complex model is not always better than a simple one. If the neural network doesn't have to learn complex features, which is the case here as it seems that the MFCC features are expressive enough, a simple model can do a very good job while being faster and less resource-intensive to train.

In [4]:
classifier = RFClassifier(n_estimators=100)

In [5]:
pathGender = MODELS_DIR + classifier.get_classifier_name() + DUMP_EXT
print(pathGender)
if os.path.isfile(pathGender):
    print("Begin to Load model")
    classifier.load(pathGender)
    #model.save_weights("gender_cnn_model_weight.h5")
    #json_string = model.to_json()
    #open('gender_cnn_model_json.json','w').write(json_string)
    #model.save("gender_cnn_model.h5")
else:
    print("Model file not exist.{}".format(path))

models/RFClassifier - n_est 100 - max_depth None.pkl
Begin to Load model


In [30]:
test_classifier(RFClassifier(n_estimators=100))

run_for_classifier..
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Loaded RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.0
Test accuracy - samples : 0.4727272727272727


In [28]:
test_classifier(RFClassifier(n_estimators=100))

run_for_classifier..
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Loaded RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 1.0
Test accuracy - samples : 0.5824175824175825


In [17]:
test_classifier(classifier)

run_for_classifier
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Loaded RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.969047619047619
Test accuracy - samples : 0.8715568593163971


In [20]:
test_classifier(classifier)

run_for_classifier..
Finished loading/creating features
Using classifier RFClassifier - n_est 100 - max_depth None
Loaded RFClassifier - n_est 100 - max_depth None
ModePath:models/RFClassifier - n_est 100 - max_depth None.pkl
Predicting on files...
Predicting on samples...
Test accuracy - files : 0.969047619047619
Test accuracy - samples : 0.8715568593163971
